#!/bin/bash -e

set -e

export DEBIAN_FRONTEND=noninteractive

cmd="$1"
shift

if [ -z "$cmd" ]; then
  echo "usage..."
  exit 1
fi

if [ "$cmd" == "install" ]; then
  cat /app/veth
elif [ -f "/app/tools/scripts/${cmd}.js" ]; then
  eval "node /app/tools/scripts/${cmd}.js $@"
else
  eval "$cmd $@"
fi

