#!/bin/bash -e

set -e

export DEBIAN_FRONTEND=noninteractive

export VETH_IMAGE=${VETH_IMAGE:="binocarlos/veth"}

function run() {
  docker run -ti --rm \
    --name veth \
    -v $PWD:/app \
    $VETH_IMAGE "$@"
}

eval run "$@"